// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: action.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ActionHandlerClient is the client API for ActionHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActionHandlerClient interface {
	DoAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
}

type actionHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewActionHandlerClient(cc grpc.ClientConnInterface) ActionHandlerClient {
	return &actionHandlerClient{cc}
}

func (c *actionHandlerClient) DoAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, "/voice.ActionHandler/DoAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActionHandlerServer is the server API for ActionHandler service.
// All implementations must embed UnimplementedActionHandlerServer
// for forward compatibility
type ActionHandlerServer interface {
	DoAction(context.Context, *ActionRequest) (*ActionResponse, error)
	mustEmbedUnimplementedActionHandlerServer()
}

// UnimplementedActionHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedActionHandlerServer struct {
}

func (UnimplementedActionHandlerServer) DoAction(context.Context, *ActionRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoAction not implemented")
}
func (UnimplementedActionHandlerServer) mustEmbedUnimplementedActionHandlerServer() {}

// UnsafeActionHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActionHandlerServer will
// result in compilation errors.
type UnsafeActionHandlerServer interface {
	mustEmbedUnimplementedActionHandlerServer()
}

func RegisterActionHandlerServer(s grpc.ServiceRegistrar, srv ActionHandlerServer) {
	s.RegisterService(&ActionHandler_ServiceDesc, srv)
}

func _ActionHandler_DoAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionHandlerServer).DoAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voice.ActionHandler/DoAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionHandlerServer).DoAction(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActionHandler_ServiceDesc is the grpc.ServiceDesc for ActionHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActionHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice.ActionHandler",
	HandlerType: (*ActionHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoAction",
			Handler:    _ActionHandler_DoAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "action.proto",
}
